messages:
  prefix: "&8[&c&lLifeCore&8] &r"
  no_permission: "&cNon hai il permesso."
  player_not_found: "&cGiocatore non trovato."
  player_only: "&cComando solo per i giocatori."
  invalid_usage: "&cUsa: {usage}"
  invalid_amount: "&cSpecifica un valore valido."
  heart_added: "&aHai aggiunto con successo &c{amount} cuore(i) &aa &f{player}&a."
  heart_removed: "&aHai rimosso con successo &c{amount} cuore(i) &aa &f{player}&a."
  heart_list_player: "&f{player} &aha &c{hearts} cuore(i)&a."
  heart_list_header: "&4&lCUORI &c&lGIOCATORI"
  heart_list_format: "&8* &f{player} &c{hearts} cuore(i)"
  heart_list_footer: ""
  hearts_limit_reached: "&cHai raggiunto il limite massimo di cuori (&e20&c)!"
  hearts_limit_reached_admin: "&cIl giocatore &e{player} &cha raggiunto il limite massimo di cuori (&e{max_hearts}&c)!"
  killer_heart_gained: "&aHai guadagnato &c1 cuore &auccidendo &f{victim}&a!"
  victim_heart_lost: "&cHai perso &c1 cuore &cper essere stato ucciso da &f{killer}&c!"
  suicide_warning: "&cAttenzione: Se ti uccidi altre {remaining} volte, verrai bannato!"
  suicide_banned: "&cSei stato bannato per esserti ucciso troppe volte da solo!"
  heart_bought: "&aHai acquistato con successo &c1 cuore&a!"
  heart_redeemed: "&aHai riscattato con successo &c1 cuore&a!"
  not_enough_money: "&cNon hai abbastanza soldi!"
  ban_command_success: "&aIl giocatore {player} è stato bannato per {time}."
  unban_command_success: "&aIl giocatore {player} è stato unbannato."
  banned_message: "&cSei stato bannato dal server per {time}!\n&ePuoi sbannarti usando &6/lifecore buy"
  unbanned_message: "&aSei stato unbannato dalla lifesteal!"
  unban_bought: "&aHai acquistato con successo l'unban! Ora puoi tornare a giocare."
  already_unbanned: "&cNon sei bannato e non per questo non puoi acquistare un UnBan!"
  no_hearts_remaining: "&cNon hai più cuori e sei stato bannato!"
  max_hearts_reached: "&cHai raggiunto il numero massimo di cuori!"
  inventory_full: "&cIl tuo inventario è pieno."
  help_header: "&c&lLIFESTEAL &7- &e&lCOMANDI UTENTI"
  help_command: "&c/lifecore help &8- &7Mostra tutti i comandi per gli utenti"
  buy_command: "&c/lifecore buy &8- &7Apri il menu della lifesteal"
  admin_help_command: "&c/lifecoreadmin &8- &7Mostra tutti i comandi per gli admin"
  admin_help_header: "&c&lLIFESTEAL &7- &6&lCOMANDI ADMIN"
  admin_help_heart_add: "&c/lifecoreadmin heart add [player] [amount] &8- &7Aggiungi i cuori ad un giocatore"
  admin_help_heart_remove: "&c/lifecoreadmin heart remove [player] [amount] &8- &7Rimuovi i cuori di un giocatore"
  admin_help_heart_list: "&c/lifecoreadmin heart list [player/all] &8- &7Lista cuori di un giocatore o di tutti i giocatori"
  admin_help_ban: "&c/lifecoreadmin ban [player] [time] &8- &7Banna un giocatore per un determinato tempo"
  admin_help_unban: "&c/lifecoreadmin unban [player] &8- &7Sbanna un giocatore"
  admin_help_footer: ""

settings:
  max_hearts: 20
  default_hearts: 10
  suicide_ban_count: 3
  suicide_ban_time: 7d
  death_ban_time: 4d
  starting_hearts_after_unban: 6
  enable_economy: true

economy:
  heart_price: 50000
  unban_price: 150000

gui:
  buy_menu:
    title: "&8Lifesteal Menu"
    rows: 3
    heart_item:
      material: "NETHER_STAR"
      name: "&cCuore"
      slot: 12
      lore:
        - "&8&m--------------------"
        - "&f• &7Acquista un cuore extra!"
        - "&f• &7Costo: &e%economy_heart_price% $"
        - "&f• &7Soldi: &e$%economy_balance%"
        - ""
        - "%economy_enough_heart%"
        - "&8&m--------------------"
    unban_item:
      material: "END_CRYSTAL"
      name: "&bUnBan"
      slot: 14
      lore:
        - "&8&m--------------------"
        - "&f• &7Acquista il tuo unban istantaneamente!"
        - "&f• &7Costo: &e%economy_unban_price% $"
        - "&f• &7Soldi: &e$%economy_balance%"
        - ""
        - "%economy_enough_unban%"
        - "&8&m--------------------"

commands:
  lifecore:
    permission: "lifecore.use"
    aliases:
      - lc
      - life
  lifecore_buy:
    permission: "lifecore.buy"
    aliases:
      - lcbuy
      - lifebuy
  lifecore_help:
    permission: "lifecore.help"
    aliases:
      - lchelp
      - lifehelp
  lifecoreadmin:
    permission: "lifecoreadmin.use"
    aliases:
      - lca
      - lifeadmin
  lifecoreadmin_help:
    permission: "lifecoreadmin.help"
  lifecoreadmin_heart_add:
    permission: "lifecoreadmin.heart.add"
  lifecoreadmin_heart_remove:
    permission: "lifecoreadmin.heart.remove"
  lifecoreadmin_heart_list:
    permission: "lifecoreadmin.heart.list"
  lifecoreadmin_ban:
    permission: "lifecoreadmin.ban"
  lifecoreadmin_unban:
    permission: "lifecoreadmin.unban"