name: LifeCore
version: '1.2'
main: it.blacked.lifestealcore.LifeCore
api-version: '1.21'
depend: [Vault, PlaceholderAPI]
authors: [blacked104]
description: Lifesteal Core for Beffax
commands:
  lifecore:
    description: Main command for LifeCore
    aliases: [lc]
  lifecoreadmin:
    description: Admin command for LifeCore
    aliases: [lca]
  spawn:
    description: Teleport player to Spawn
  setspawn:
    description: Set the player Spawn
  rtp:
    description: Teleport player to random position
  randomtp:
    description: Teleport player to random position
  wild:
    description: Teleport player to random position
  shop:
    description: Open player Shop
  stats:
    description: Show ur or other player stats
  ping:
    description: View ur or other player's ping